import Foundation
import SwiftUI

// MARK: - IntelBriefView
// Figma frame 6, Variant A — 03 // DAILY_INTEL_BRIEF + 03 // MARKET_SIGNALS.
// Left column: 5-signal brief generated by qwen2.5:0.5b via Ollama.
// Right column: 4 status cards derived from news keyword counts + MarketBenchmarks.

struct IntelBriefView: View {

    let deals: [PropertyDeal]
    let marketId: String?

    @State private var briefState: BriefState = .idle
    @State private var signals: [IntelSignal] = []
    @State private var errorMessage: String = ""

    private let accent = ProfileType.globalIntelligence.accentColor
    private let news   = NewsAggregatorService.shared

    var body: some View {
        HStack(spacing: 0) {
            briefColumn
            TerminalStructuralDivider()
            signalsColumn
        }
        .frame(maxWidth: .infinity, maxHeight: .infinity)
        .background(DesignTokens.canvasBase)
        .task { await generateIfStale() }
        .onChange(of: marketId ?? "") { _, _ in Task { await generateIfStale() } }
    }

    // MARK: - Brief column (left ~60%)

    private var briefColumn: some View {
        TerminalBlock(command: briefCommand, accentColor: accent) {
            VStack(alignment: .leading, spacing: 0) {
                switch briefState {
                case .idle:
                    Text("// INITIALISING …")
                        .porteosMeta()
                        .foregroundStyle(DesignTokens.textDim)

                case .generating:
                    HStack(spacing: 8) {
                        ProgressView().scaleEffect(0.6).tint(accent)
                        Text("// SCANNING MARKET …")
                            .porteosMeta()
                            .foregroundStyle(DesignTokens.textDim)
                    }

                case .ready:
                    briefSignalList

                case .offline:
                    offlineFallback

                case .error:
                    VStack(alignment: .leading, spacing: 6) {
                        Text("// BRIEF_ERROR")
                            .porteosMeta()
                            .foregroundStyle(DesignTokens.statusWarn)
                        Text(errorMessage)
                            .porteosMeta()
                            .foregroundStyle(DesignTokens.textSecondary)
                            .fixedSize(horizontal: false, vertical: true)
                        regenerateButton
                    }
                }

                Spacer(minLength: 0)

                Divider().background(DesignTokens.dividerStructural).padding(.vertical, 10)

                HStack {
                    Text("// LOCAL LLM · NO DATA LEAVES DEVICE")
                        .porteosMeta()
                        .foregroundStyle(DesignTokens.textDim)
                    Spacer()
                    regenerateButton
                }
            }
        }
        .padding(DesignTokens.blockGutter)
        .frame(maxWidth: .infinity)
    }

    private var briefCommand: String {
        let month = Calendar.current.component(.month, from: Date())
        let year  = Calendar.current.component(.year, from: Date())
        let mm    = String(format: "%02d", month)
        return "03 // DAILY_INTEL_BRIEF [\(year)-\(mm)]"
    }

    private var briefSignalList: some View {
        VStack(alignment: .leading, spacing: 8) {
            ForEach(Array(signals.enumerated()), id: \.offset) { idx, signal in
                HStack(alignment: .top, spacing: 8) {
                    Text(">")
                        .porteosMeta()
                        .foregroundStyle(accent)
                    VStack(alignment: .leading, spacing: 2) {
                        Text("SIGNAL \(String(format: "%02d", idx + 1))")
                            .porteosMeta()
                            .foregroundStyle(accent)
                        Text(signal.text)
                            .porteosMeta()
                            .foregroundStyle(DesignTokens.textSecondary)
                            .fixedSize(horizontal: false, vertical: true)
                    }
                }
            }
        }
    }

    private var offlineFallback: some View {
        VStack(alignment: .leading, spacing: 8) {
            Text("// AGENT_OFFLINE")
                .porteosMeta()
                .foregroundStyle(DesignTokens.statusWarn)
            Text("Local model not running. Start Ollama:")
                .porteosMeta()
                .foregroundStyle(DesignTokens.textSecondary)
            Text("Terminal → ollama serve")
                .porteosMeta()
                .foregroundStyle(DesignTokens.textDim)
            HStack(spacing: 8) {
                regenerateButton
                Button { briefState = .idle } label: {
                    Text("[ DISMISS ]")
                        .porteosMeta()
                        .foregroundStyle(DesignTokens.textDim)
                }
                .buttonStyle(.plain)
            }
            .padding(.top, 4)
        }
    }

    private var regenerateButton: some View {
        Button {
            Task { await generate() }
        } label: {
            Text(briefState == .generating ? "[ … ]" : "[ REGENERATE ]")
                .porteosMeta()
                .foregroundStyle(accent)
        }
        .buttonStyle(.plain)
        .disabled(briefState == .generating)
    }

    // MARK: - Market Signals column (right ~40%)

    private var signalsColumn: some View {
        TerminalBlock(command: "03 // MARKET_SIGNALS", accentColor: accent) {
            VStack(alignment: .leading, spacing: 8) {
                let cards = marketSignalCards
                ForEach(cards) { card in
                    signalCard(card)
                }
                Spacer(minLength: 0)
            }
        }
        .padding(DesignTokens.blockGutter)
        .frame(maxWidth: 280)
    }

    private func signalCard(_ card: MarketSignalCard) -> some View {
        VStack(alignment: .leading, spacing: 2) {
            Text(card.rating)
                .font(.system(size: 14, weight: .bold, design: .monospaced))
                .foregroundStyle(card.ratingColor)
            Text(card.label)
                .porteosMeta()
                .foregroundStyle(DesignTokens.textDim)
        }
        .padding(.horizontal, 10)
        .padding(.vertical, 8)
        .frame(maxWidth: .infinity, alignment: .leading)
        .background(DesignTokens.surfacePanel)
        .overlay { Rectangle().strokeBorder(DesignTokens.dividerStructural, lineWidth: 1) }
    }

    // MARK: - Signal derivation

    private var articles: [IntelNewsArticle] {
        news.articles(marketId: marketId, dealMarketId: nil, withinDays: 60)
    }

    private var marketSignalCards: [MarketSignalCard] {
        let regCount     = articles.filter { $0.topics.contains(IntelSector.energy.rawValue) }.count
        let rateCount    = articles.filter { $0.topics.contains(IntelSector.capMarkets.rawValue) }.count
        let tourismCount = articles.filter { $0.topics.contains(IntelSector.travel.rawValue) }.count
        let reCount      = articles.filter { $0.topics.contains(IntelSector.realEstate.rawValue) }.count

        return [
            MarketSignalCard(
                label: "REG. PRESSURE",
                rating: regCount >= 2 ? "HIGH" : regCount == 1 ? "MODERATE" : "LOW",
                ratingColor: regCount >= 2 ? DesignTokens.statusWarn : regCount == 1 ? .yellow : DesignTokens.statusGo
            ),
            MarketSignalCard(
                label: "RATE OUTLOOK",
                rating: rateCount >= 2 ? "VOLATILE" : "STABLE",
                ratingColor: rateCount >= 2 ? DesignTokens.statusWarn : DesignTokens.textPrimary
            ),
            MarketSignalCard(
                label: "TOURISM INDEX",
                rating: tourismCount >= 1 ? "POSITIVE" : "NEUTRAL",
                ratingColor: tourismCount >= 1 ? DesignTokens.statusGo : DesignTokens.textDim
            ),
            MarketSignalCard(
                label: "SUPPLY PIPELINE",
                rating: reCount >= 3 ? "ACTIVE" : reCount >= 1 ? "MODERATE" : "TIGHT",
                ratingColor: reCount >= 3 ? DesignTokens.statusGo : reCount >= 1 ? .yellow : DesignTokens.statusWarn
            ),
        ]
    }

    // MARK: - Ollama generation

    private var lastGeneratedKey: String {
        "intel_brief_last_\(marketId ?? "all")"
    }

    private func generateIfStale() async {
        let key = lastGeneratedKey
        if let last = UserDefaults.standard.object(forKey: key) as? Date,
           Date().timeIntervalSince(last) < 8 * 3600,
           !signals.isEmpty {
            return
        }
        await generate()
    }

    private func generate() async {
        briefState = .generating
        signals = []

        guard let url = URL(string: "http://localhost:11434/api/generate") else {
            briefState = .offline
            return
        }

        // Build context from cached news + in-scope deals
        let currentArticles = articles  // capture once
        let contextArticles = currentArticles.prefix(12).map { "- \($0.title)" }.joined(separator: "\n")
        let dealNames = deals
            .filter { marketId == nil || $0.marketId == marketId || MarketFeedRegistry.countryId(for: $0.marketId) == marketId }
            .prefix(6)
            .map { "\($0.propertyName) (\($0.status.rawValue))" }
            .joined(separator: ", ")

        let market = marketId.flatMap { MarketFeedRegistry.market(id: $0)?.displayName } ?? "all markets"

        // If no news cached yet, surface a clear message instead of a confusing brief
        if currentArticles.isEmpty {
            signals = [
                IntelSignal(text: "No headlines cached yet — tap ./refresh --news on the MAP tab to fetch feeds, then regenerate."),
            ]
            briefState = .ready
            return
        }

        let prompt = """
You are a real estate portfolio intelligence assistant. Based on the following market news headlines and portfolio assets, generate exactly 5 brief, one-sentence market signal observations relevant to a property investor. Format each as a single sentence starting with a key observation. Be factual and concise.

Market: \(market)
Portfolio assets in scope: \(dealNames.isEmpty ? "none" : dealNames)

Recent headlines:
\(contextArticles.isEmpty ? "No headlines available." : contextArticles)

Respond with exactly 5 numbered observations (1. 2. 3. 4. 5.) with no other text.
"""

        let body: [String: Any] = [
            "model": "qwen2.5:0.5b",
            "prompt": prompt,
            "stream": false
        ]

        do {
            guard let data = try? JSONSerialization.data(withJSONObject: body) else {
                briefState = .error
                errorMessage = "Failed to encode request."
                return
            }
            var request = URLRequest(url: url, timeoutInterval: 60)
            request.httpMethod = "POST"
            request.httpBody = data
            request.setValue("application/json", forHTTPHeaderField: "Content-Type")

            let (responseData, response) = try await URLSession.shared.data(for: request)

            guard let http = response as? HTTPURLResponse, http.statusCode == 200 else {
                briefState = .offline
                return
            }

            guard let json = try? JSONSerialization.jsonObject(with: responseData) as? [String: Any],
                  let text = json["response"] as? String else {
                briefState = .error
                errorMessage = "Unexpected response from Ollama."
                return
            }

            signals = parseSignals(from: text)
            if signals.isEmpty {
                // Fallback: split by line and take up to 5 non-empty lines
                signals = text
                    .components(separatedBy: "\n")
                    .map { $0.trimmingCharacters(in: .whitespaces) }
                    .filter { !$0.isEmpty }
                    .prefix(5)
                    .map { IntelSignal(text: $0) }
            }

            UserDefaults.standard.set(Date(), forKey: lastGeneratedKey)
            briefState = .ready

        } catch let err as NSError {
            // Connection refused → Ollama not running
            if err.domain == NSURLErrorDomain && (err.code == NSURLErrorCannotConnectToHost || err.code == NSURLErrorNetworkConnectionLost) {
                briefState = .offline
            } else {
                briefState = .error
                errorMessage = err.localizedDescription
            }
        }
    }

    private func parseSignals(from text: String) -> [IntelSignal] {
        // Match "1. text", "1) text", "> text" patterns
        let lines = text.components(separatedBy: "\n")
        let pattern = #"^[\d]+[.)]\s*(.+)|^>\s*(.+)"#
        var results: [IntelSignal] = []
        for line in lines {
            let trimmed = line.trimmingCharacters(in: .whitespaces)
            if let range = trimmed.range(of: pattern, options: .regularExpression) {
                let _ = range
                // Strip leading "1. " or "> "
                let cleaned = trimmed
                    .replacingOccurrences(of: #"^[\d]+[.)]\s*"#, with: "", options: .regularExpression)
                    .replacingOccurrences(of: #"^>\s*"#, with: "", options: .regularExpression)
                    .trimmingCharacters(in: .whitespaces)
                if !cleaned.isEmpty { results.append(IntelSignal(text: cleaned)) }
            }
            if results.count == 5 { break }
        }
        return results
    }
}

// MARK: - Supporting types

struct IntelSignal: Identifiable {
    let id = UUID()
    let text: String
}

struct MarketSignalCard: Identifiable {
    let id = UUID()
    let label: String
    let rating: String
    let ratingColor: Color
}

enum BriefState {
    case idle, generating, ready, offline, error
}
